### ISSUE TITLE
Config isn't updated automatically

### ISSUE THREAD

**Issue by bobhenl** [Seggan/SlimefunWarfare#5]
```
options:
  auto-update: true

explosions:
  # Makes obsidian as weak as stone to encourage the use of reinforced concrete
  weak-obsidian: true
  concrete-explode-chance: 20
```

Now I'm using ver 9 and there's missing option to turn off auto shift shoot, will remove config to reload it, but I think it should be added automatically.
